### ISSUE TITLE
ipstack should be opt-in / optional

### ISSUE THREAD

**Issue by albjeremias** [GetTogetherComm/GetTogether#118]
I'll try to implement this myself.. but is there a way to make IPSTACK optional?

I mean the user maybe select using the map, or a list of citis, or of organizations... no?
Or even better... use an open source alternative! :)
http://lyften.com/projects/laravel-geoip/

When the API KEY is empty.. i get this error

```
 | Internal Server Error: /events/all/
get_together_1  | Traceback (most recent call last):
get_together_1  |   File "/home/python/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
get_together_1  |     response = get_response(request)
get_together_1  |   File "/home/python/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
get_together_1  |     response = self.process_exception_by_middleware(e, request)
get_together_1  |   File "/home/python/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
get_together_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
get_together_1  |   File "/home/python/get_together/views/events.py", line 69, in events_list_all
get_together_1  |     geo_ip = location.get_geoip(request)
get_together_1  |   File "/home/python/events/location.py", line 38, in get_geoip
get_together_1  |     g = get_ipstack_geocoder(client_ip)
get_together_1  |   File "/home/python/events/ipstack.py", line 104, in get_ipstack_geocoder
get_together_1  |     raise Exception("You must define IPSTACK_ACCESS_KEY in your setting to use ipstack.py geocoding")
get_together_1  | Exception: You must define IPSTACK_ACCESS_KEY in your setting to use ipstack.py geocoding
```

**Comment by albjeremias** [comment]
i think option 2, should be taken first... and then think about supporting different providers... 

and there is this one.. http://lyften.com/projects/laravel-geoip/ 
i can put it up in branch using docker-compose.. but i dunno so much about python.. :S ill try it out maybe
